
services:
  mysql:
    image: mysql:8.0
    container_name: internship_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: internship      
    ports:
      - "3306:3306"
    volumes:
      - internship_data:/var/lib/mysql
    networks:
      - internship_network

  phpmyadmin:
    image: phpmyadmin
    container_name: dtalkec_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - internship_network

  backend:
    build: .
    container_name: dtalkec_backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "8081:8081"
    environment:
      NODE_ENV: production
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: internship      
    depends_on:
      - mysql
    networks:
      - internship_network

volumes:
  internship_data:

networks:
  internship_network:
    name: internship_network