version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: internship_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: internship      
    ports:
      - "3306:3306"
    volumes:
      - internship_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: dtalkec_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

  redis:
    image: redis:latest
    container_name: dtalkec_redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Expose Redis on port 6379
    volumes:
      - redis_data:/data # Persist Redis data

volumes:
  internship_data:
  redis_data: